### ISSUE TITLE
Function not in use

### ISSUE THREAD

**Issue by dangerstephen** [dkingdon/project-01#6]
https://github.com/dkingdon/project-01/blob/master/public/scripts/admin.js#L99

See that both of these are not in use and just chilling! Maybe consider removing them.

Thanks,
Stephen & Star

**Comment by ghost** [comment]
Yes, thank you. We will remove before our final push :)

Thanks,
C

**Comment by dkingdon** [comment]
@dangerstephen 

Code removed before release candidate hit master. Thanks for the call out.
